### ISSUE TITLE
Repeated Chinese Terms Make KeywordsVocabulary Messy

### ISSUE THREAD

**Issue by l34marr** [plone/plone.app.vocabularies#15]
Repeated Chinese terms (see the two "中文" in the attached image) in the Tags field will be encoded by b2a_qp() and pollute the KeywordsVocabulary results.

![catalog-repeated-chinese](https://cloud.githubusercontent.com/assets/56113/8827596/2c9d61fc-30c0-11e5-8d66-898e7b013f24.png)

You can see this issue in action at http://www.youtube.com/watch?v=L9ksAmGpi7w

Can we use UTF-8 strings, instead of b2a_qp strings, for SimpleTerm Values?

**Comment by jensens** [comment]
screencast by @l34marr showing the effect https://www.youtube.com/watch?v=CQwh3gYoicM (copied from PR)

**Comment by jensens** [comment]
May you please check the same with latest buildout.coredev  5.0 branch? I can not reproduce the problem.

**Comment by jianaijun** [comment]
Reference https://dev.plone.org/ticket/15022

2015-07-30 22:33 GMT+08:00 Jens W. Klein <notifications@github.com>:

**Comment by jensens** [comment]
since the vocabulary itself is fine and follows the rules, I expect an issue in plone.app.widgets/mockup.

@jianaijun can you do me a favor and checkout latest buildout.coredev 5.0 branch and proof is the problem is still valid? if this is the case it would be great to create a new ticket at https://github.com/plone/Products.CMFPlone/issues referencing this ticket and the old one at dev.plone.org

**Comment by l34marr** [comment]
@jensens We do test with the latest buildout.coredev 5.0 branch and looks good. But, is this issue fixed by https://github.com/plone/plone.app.vocabularies/commit/a48de492e503929fe512daf504ca8319f0e109b9 ?

**Comment by jensens** [comment]
i more think someone fixed mockup. but if this is fine i close the bug here
