### ISSUE TITLE
Deprecate zope.formlib

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.vocabularies#38]
A quick search reveals some usage as well: https://github.com/plone/plone.app.vocabularies/search?utf8=%E2%9C%93&q=formlib&type=Code

Is there any porting guide out of it? Should that be replaced by z3c.form?

**Comment by jensens** [comment]
**What we have**

From formlib theres only the ``ISourceQueryView`` interface used:

- Interface https://github.com/zopefoundation/zope.formlib/blob/master/src/zope/formlib/interfaces.py#L334
- Usage https://github.com/plone/plone.app.vocabularies/search?utf8=%E2%9C%93&q=ISourceQueryView&type=Code

I seems this is an old definition for what then was expressed by ``zope.browser.interfaces.ITerms`` https://github.com/zopefoundation/zope.browser/blob/master/src/zope/browser/interfaces.py#L88

But even this is kind of deprecated, because the "All source implementations will be deprecated" https://github.com/plone/plone.app.vocabularies/blob/ad75d57274ae33ee0d6e8a06e6ce5079428b1ca1/plone/app/vocabularies/configure.zcml#L162

**Proposed Solution:** 
- Really deprecate all source implemenations (let them emit a DeprecationWarning), see http://docs.plone.org/develop/styleguide/deprecation.html
- conditional import from zope.formlib, if not available provide stub Interface
- conditional registration in zcml (only if zope.formlib is available)
- mark code for removal in Plone 6
