### ISSUE TITLE
Newlines in tokens break AjaxSelectFieldWidget

### ISSUE THREAD

**Issue by flipmcf** [plone/plone.app.vocabularies#64]
See https://community.plone.org/t/tags-subject-field-mangling-long-terms/13067

b2a_qp() [ https://docs.python.org/3/library/binascii.html#binascii.b2a_qp ] adds newlines every 76 bytes.  These newlines are interpreted badly by javascript.   The vocabularies we provide to the browser must contain newline-free tokens.

**Comment by jensens** [comment]
It violates the interface https://zopeschema.readthedocs.io/en/latest/api.html#zope.schema.interfaces.ITokenizedTerm

**Comment by witsch** [comment]
I think we recently ran into this problem as well — it sounds very similar at least… 🙂 

We've fixed it locally since we already had a separate adapter for the widget in place:
```diff
--- a/.../browser/widgets/keywords.py
+++ b/.../browser/widgets/keywords.py
@@ -34,8 +34,20 @@ class KeywordsWidget(select.SelectWidget):
 
 
+class SubjectsWidget(KeywordsWidget):
+
+    def extract(self, *args, **kw):
+        value = self.request.get(self.name)
+        if value is not None:
+            # fix mangled newline due to quoted-printable
+            # encoding and form roundtrip... :p
+            value = [v.replace('=\r\n', '=\n') for v in value]
+            self.request.set(self.name, value)
+        return super(KeywordsWidget, self).extract(*args, **kw)
+
+
 @adapter(getSpecification(ICategorization['subjects']), IPloneFormLayer)
 @implementer(IFieldWidget)
 def SubjectsFieldWidget(field, request, *args, **kw):
     field.value_type = Choice(vocabulary='plone.app.vocabularies.Keywords')
-    return FieldWidget(field, KeywordsWidget(request))
+    return FieldWidget(field, SubjectsWidget(request))
```

The underlying issue seems to be the "quoted-printable" encoding introduced in c16313a8 (cc-ing @mjpieters 👋). As a side-effect long tokens will be split into multiple lines, i.e. contain occurences of `=\n`. During the browser roundtrip this got turned into `=\r\n` in our case, after which the token can no longer be found, of course.

The above is a rather crude hack, but fixing the corresponding ["data converters" in `z3c.form`](https://z3cform.readthedocs.io/en/latest/informative/converter.html) didn't work, because they are called to late (i.e. after the `extract`)…

Hope this helps a bit.

**Comment by mjpieters** [comment]
Looks like I didn't realise that `binascii.b2a_qp()` would introduce line separators at the time (even though it does state so in the docs).

I guess ya'll have to replace that call with some other binary -> ASCII-safe subset conversion. I _think_ I picked quoted-printable at the time because it keeps readable ASCII-safe token values readable. If readability is not an issue, I'd just go with (URL-safe) Base64. If readability is a goal, then perhaps use Base64 as a fallback if quoted-printable produces output with line separators:

```
from base64 import urlsafe_b64encode

def ascii_line_safe_token_value(value):
    """Vocabulary term tokens *must* be 7 bit values without line separators"""
    value = safe_encode(value)
    encoded = b2a_qp(value)
    if b'\n' not in encoded:
        return encoded
    # no newlines allowed, fall back to base64
    return urlsafe_b64encode(value)

def safe_simpleterm_from_value(value):
    """create SimpleTerm from an untrusted value.
    - token needs cleaning up: Vocabulary term tokens *must* be 7 bit values and not contain line separators
    - anything for display has to be cleaned up, titles *must* be unicode
    """
    return SimpleTerm(value, ascii_line_safe_token_value(value), safe_unicode(value))
```

I don't know (almost a decade after I last touched this stuff)  if the keyword index can contain line separators in values? If so, then you need a different encoding anyway.

@witch: instead of replacing `=\r\n` with `=\n`, you could also decode and re-encode, so `b2a_qp(a2b_qp(token))`. `binascii.a2b_qp()` doesn't care what line separators are used, you can even use a mix of `=\n`, `=\r` and `=\r\n` sequences.

**Comment by jensens** [comment]
> I _think_ I picked quoted-printable at the time because it keeps readable ASCII-safe token values readable. If readability is not an issue, I'd just go with (URL-safe) Base64.

I do not think readability of the token is primary important, but it is nice to have. The current pull request is based on base64 for the values which are not ASCII convertible already. I think this is a good compromise.

**Comment by mauritsvanrees** [comment]
PR #65 was merged and I have released `plone.app.vocabularies 4.2.2`.
